import jsPDF from 'jspdf';
import type { MaterialEstimate } from './materials';
import { formatArea, formatPitch, formatNumber } from './geometry';

/**
 * EagleView-style page templates for PDF reports.
 * Provides consistent headers, footers, page numbers, and
 * reusable page layouts that match the EagleView Premium Report format.
 */

// ─── Constants ─────────────────────────────────────────────────────────

/** 0.75 inches in mm */
export const PAGE_MARGIN = 19.05;

/** Font sizes matching EagleView's professional typography */
export const FONT_SIZES = {
  title: 16,
  sectionHeader: 12,
  body: 12,
  caption: 10,
  small: 8,
  footer: 7,
} as const;

/** Color palette */
export const COLORS = {
  primary: [37, 120, 235] as [number, number, number],
  darkText: [30, 30, 30] as [number, number, number],
  grayText: [120, 120, 120] as [number, number, number],
  lightBg: [245, 245, 245] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  lightBlue: [219, 234, 254] as [number, number, number],
  headerBg: [37, 120, 235] as [number, number, number],
} as const;

// ─── Data Interfaces ──────────────────────────────────────────────────

export interface ReportSummaryData {
  totalAreaSquares: number;
  predominantPitch: number;
  numberOfFacets: number;
  totalRidgeHipLf: number;
  totalValleyLf: number;
  totalRakeEaveLf: number;
}

export interface FacetDetail {
  name: string;
  pitch: number;
  areaSqFt: number;
  trueAreaSqFt: number;
}

// ─── Page Header ──────────────────────────────────────────────────────

/**
 * Add a consistent page header with property address and report date.
 * Renders a thin bar at the top of the page.
 */
export function addPageHeader(
  doc: jsPDF,
  propertyAddress: string,
  reportDate: string
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = PAGE_MARGIN;

  // Header bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 10, 'F');

  // Address on the left
  doc.setFontSize(FONT_SIZES.small);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.white);
  doc.text(propertyAddress, margin, 7);

  // Date on the right
  const dateWidth = doc.getTextWidth(reportDate);
  doc.text(reportDate, pageWidth - margin - dateWidth, 7);
}

// ─── Page Footer ──────────────────────────────────────────────────────

/**
 * Add a consistent footer with company branding.
 */
export function addPageFooter(
  doc: jsPDF,
  companyName: string
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer background
  doc.setFillColor(...COLORS.lightBg);
  doc.rect(0, pageHeight - 14, pageWidth, 14, 'F');

  // Footer text
  doc.setFontSize(FONT_SIZES.footer);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');

  const footerText = `Generated by SkyHawk Aerial Property Intelligence | ${companyName}`;
  doc.text(footerText, pageWidth / 2, pageHeight - 8, { align: 'center' });
  doc.text(
    'Measurements powered by Google Solar API + AI Vision',
    pageWidth / 2,
    pageHeight - 4,
    { align: 'center' }
  );
}

// ─── Page Number ──────────────────────────────────────────────────────

/**
 * Add "Page X of Y" in the bottom right corner.
 */
export function addPageNumber(
  doc: jsPDF,
  pageNum: number,
  totalPages: number
): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = PAGE_MARGIN;

  const text = `Page ${pageNum} of ${totalPages}`;
  doc.setFontSize(FONT_SIZES.footer);
  doc.setTextColor(150, 150, 150);
  doc.setFont('helvetica', 'normal');
  const textWidth = doc.getTextWidth(text);
  doc.text(text, pageWidth - margin - textWidth, pageHeight - 8);
}

// ─── Summary Page ─────────────────────────────────────────────────────

/**
 * Render a professional summary page with key metrics in a 2x3 grid layout.
 * Returns the next available Y position on the page.
 */
export function renderSummaryPage(
  doc: jsPDF,
  data: ReportSummaryData
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = PAGE_MARGIN;
  const contentWidth = pageWidth - margin * 2;
  let y = margin + 14; // offset for header

  // Section title
  doc.setFontSize(FONT_SIZES.title);
  doc.setTextColor(...COLORS.primary);
  doc.setFont('helvetica', 'bold');
  doc.text('KEY METRICS SUMMARY', margin, y);
  y += 4;

  // Horizontal rule
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // 2x3 grid of metric cards
  const metrics = [
    { label: 'Total Area', value: formatNumber(data.totalAreaSquares, 1), unit: 'squares' },
    { label: 'Predominant Pitch', value: formatPitch(data.predominantPitch), unit: '' },
    { label: 'Number of Facets', value: String(data.numberOfFacets), unit: '' },
    { label: 'Total Ridge/Hip', value: formatNumber(data.totalRidgeHipLf, 0), unit: 'lf' },
    { label: 'Total Valley', value: formatNumber(data.totalValleyLf, 0), unit: 'lf' },
    { label: 'Total Rake/Eave', value: formatNumber(data.totalRakeEaveLf, 0), unit: 'lf' },
  ];

  const cols = 2;
  const cardWidth = (contentWidth - 6) / cols; // 6mm gap between columns
  const cardHeight = 28;
  const cardGap = 6;

  for (let i = 0; i < metrics.length; i++) {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const cardX = margin + col * (cardWidth + cardGap);
    const cardY = y + row * (cardHeight + cardGap);

    // Card background
    doc.setFillColor(...COLORS.lightBg);
    doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 2, 2, 'F');

    // Accent bar on left
    doc.setFillColor(...COLORS.primary);
    doc.rect(cardX, cardY, 3, cardHeight, 'F');

    // Label
    doc.setFontSize(FONT_SIZES.caption);
    doc.setTextColor(...COLORS.grayText);
    doc.setFont('helvetica', 'normal');
    doc.text(metrics[i].label, cardX + 8, cardY + 10);

    // Value
    doc.setFontSize(14);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    const valueStr = metrics[i].unit ? `${metrics[i].value} ${metrics[i].unit}` : metrics[i].value;
    doc.text(valueStr, cardX + 8, cardY + 22);
  }

  y += Math.ceil(metrics.length / cols) * (cardHeight + cardGap) + 4;
  return y;
}

// ─── Facet Detail Page ────────────────────────────────────────────────

/**
 * Render a facet detail table. Returns the next page number.
 */
export function renderFacetDetailPage(
  doc: jsPDF,
  facets: FacetDetail[],
  startPage: number
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = PAGE_MARGIN;
  const contentWidth = pageWidth - margin * 2;
  let y = margin + 14;

  // Section title
  doc.setFontSize(FONT_SIZES.title);
  doc.setTextColor(...COLORS.primary);
  doc.setFont('helvetica', 'bold');
  doc.text('FACET DETAILS', margin, y);
  y += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 6;

  // Table header
  doc.setFillColor(...COLORS.primary);
  doc.rect(margin, y - 4, contentWidth, 7, 'F');
  doc.setFontSize(FONT_SIZES.small);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('Facet', margin + 3, y);
  doc.text('Pitch', margin + contentWidth * 0.35, y);
  doc.text('Flat Area', margin + contentWidth * 0.52, y);
  doc.text('True Area', margin + contentWidth * 0.70, y);
  doc.text('Squares', margin + contentWidth * 0.88, y);
  y += 7;

  let totalFlatArea = 0;
  let totalTrueArea = 0;
  let totalSquares = 0;

  for (let i = 0; i < facets.length; i++) {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + 10 > pageHeight - margin - 14) {
      doc.addPage();
      startPage++;
      y = margin + 14;
    }

    const facet = facets[i];
    const facetSquares = facet.trueAreaSqFt / 100;
    const rowY = y;

    if (i % 2 === 0) {
      doc.setFillColor(...COLORS.lightBg);
      doc.rect(margin, rowY - 4, contentWidth, 7, 'F');
    }

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'normal');
    doc.text(facet.name, margin + 3, rowY);
    doc.text(formatPitch(facet.pitch), margin + contentWidth * 0.35, rowY);
    doc.setTextColor(...COLORS.grayText);
    doc.text(formatArea(facet.areaSqFt), margin + contentWidth * 0.52, rowY);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'bold');
    doc.text(formatArea(facet.trueAreaSqFt), margin + contentWidth * 0.70, rowY);
    doc.setFont('helvetica', 'normal');
    doc.text(formatNumber(facetSquares, 1), margin + contentWidth * 0.88, rowY);

    totalFlatArea += facet.areaSqFt;
    totalTrueArea += facet.trueAreaSqFt;
    totalSquares += facetSquares;
    y += 7;
  }

  // Totals row
  if (facets.length > 0) {
    doc.setFillColor(...COLORS.lightBlue);
    doc.rect(margin, y - 4, contentWidth, 7, 'F');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.primary);
    doc.setFont('helvetica', 'bold');
    doc.text('TOTAL', margin + 3, y);
    doc.text(formatArea(totalFlatArea), margin + contentWidth * 0.52, y);
    doc.text(formatArea(totalTrueArea), margin + contentWidth * 0.70, y);
    doc.text(formatNumber(totalSquares, 1), margin + contentWidth * 0.88, y);
  }

  return startPage;
}

// ─── Material Estimate Page ───────────────────────────────────────────

/**
 * Render a material estimate table. Returns the next page number.
 */
export function renderMaterialEstimatePage(
  doc: jsPDF,
  materials: MaterialEstimate,
  startPage: number
): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = PAGE_MARGIN;
  const contentWidth = pageWidth - margin * 2;
  let y = margin + 14;

  // Section title
  doc.setFontSize(FONT_SIZES.title);
  doc.setTextColor(...COLORS.primary);
  doc.setFont('helvetica', 'bold');
  doc.text('MATERIAL ESTIMATE', margin, y);
  y += 4;

  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageWidth - margin, y);
  y += 3;

  doc.setFontSize(FONT_SIZES.footer);
  doc.setTextColor(...COLORS.grayText);
  doc.setFont('helvetica', 'normal');
  doc.text(
    'Quantities are approximate and may vary by material type and installation method.',
    margin, y
  );
  y += 6;

  const materialRows: [string, string, string][] = [
    ['Shingle Bundles', String(materials.shingleBundles), '3 bundles per square'],
    ['Underlayment', `${materials.underlaymentRolls} rolls`, '~4 squares per roll'],
    ['Ice & Water Shield', `${materials.iceWaterRolls} rolls`, 'At eave edges'],
    ['Starter Strip', `${materials.starterStripLf} lf`, 'Eave + rake perimeter'],
    ['Ridge Cap', `${materials.ridgeCapLf} lf`, 'Ridge + hip lines'],
    ['Drip Edge', `${materials.dripEdgeLf} lf`, 'Eave + rake edges'],
    ['Step Flashing', `${materials.stepFlashingPcs} pcs`, 'Wall junctions'],
    ['Pipe Boots', `${materials.pipeBoots} pcs`, 'Est. 1 per 1,000 sq ft'],
    ['Roofing Nails', `${materials.nailsLbs} lbs`, '~1.75 lbs per square'],
    ['Caulk', `${materials.caulkTubes} tubes`, '1 per 25 lf flashing'],
    ['Ridge Vent', `${materials.ridgeVentLf} lf`, 'Full ridge length'],
  ];

  // Filter zero-quantity rows
  const activeRows = materialRows.filter((r) => !r[1].startsWith('0'));

  // Table header
  doc.setFillColor(...COLORS.primary);
  doc.rect(margin, y - 4, contentWidth, 7, 'F');
  doc.setFontSize(FONT_SIZES.small);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.white);
  doc.text('Material', margin + 3, y);
  doc.text('Quantity', margin + contentWidth * 0.45, y);
  doc.text('Basis', margin + contentWidth * 0.7, y);
  y += 7;

  for (let i = 0; i < activeRows.length; i++) {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + 10 > pageHeight - margin - 14) {
      doc.addPage();
      startPage++;
      y = margin + 14;
    }

    const rowY = y;
    if (i % 2 === 0) {
      doc.setFillColor(...COLORS.lightBg);
      doc.rect(margin, rowY - 4, contentWidth, 7, 'F');
    }

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.darkText);
    doc.setFont('helvetica', 'normal');
    doc.text(activeRows[i][0], margin + 3, rowY);
    doc.setFont('helvetica', 'bold');
    doc.text(activeRows[i][1], margin + contentWidth * 0.45, rowY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.grayText);
    doc.text(activeRows[i][2], margin + contentWidth * 0.7, rowY);

    y += 7;
  }

  return startPage;
}

/**
 * Apply headers, footers, and page numbers to all pages in the document.
 * Call this after all content has been added.
 */
export function applyPageDecoration(
  doc: jsPDF,
  propertyAddress: string,
  reportDate: string,
  companyName: string,
  startFromPage: number = 2 // skip hero page
): void {
  const totalPages = doc.getNumberOfPages();
  for (let i = startFromPage; i <= totalPages; i++) {
    doc.setPage(i);
    addPageHeader(doc, propertyAddress, reportDate);
    addPageFooter(doc, companyName);
    addPageNumber(doc, i, totalPages);
  }
}

/**
 * Format page number text for display.
 * Used externally for testing page number formatting.
 */
export function formatPageNumber(pageNum: number, totalPages: number): string {
  return `Page ${pageNum} of ${totalPages}`;
}
